version: "3"
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    # image: blog-backend
    container_name: blog-backend
    ports:
      - "3000:3000"
    # restart: always
    # volumes:
    #   - ./:/app
